name: nasdaq_data_producer
language: Python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: nasdaq_stocks
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
